### PR TITLE
Update CoinBlockerLists URL.

### PR DESCRIPTION
**Pull request by ZeroDot1**
CoinBlockerLists LICENSE: https://zerodot1.gitlab.io/CoinBlockerLists/LICENSE

### CODE REVIEW

**Comment by ZeroDot1** [comment]
Details about the CoinBlockerLists can be found on the homepage.

https://zerodot1.gitlab.io/CoinBlockerListsWeb/downloads.html#

**Review by spirillen — COMMENTED** [review]
It is on purpose I'll take directly from the repo, to avoid any delayed / outdated cache mechanism

Would the Current URI still match your suggestion?

And thanks for your warm thought of keeping the source list up to date

**Comment by ZeroDot1** [comment]
Via the link the list is always up to date and the list is gzip compressed so that there are less problems with the download and the servers are not so heavily loaded.

**Comment by ZeroDot1** [comment]
By the way, I recommend to use CURL with the following parameters, this makes the whole thing more stable.

`curl  --tcp-fastopen --tcp-nodelay --tr-encoding --compressed --http2 --ignore-content-length`

**Comment by spirillen** [comment]
In case I should switch to curl I should also append `--retry 5` to minimize the risk of download errors.

```
curl -h | grep retry
     --retry <num>   Retry request if transient problems occur
```

**Pull request merged**
